name: Deploy to EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to Instance 1
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/ssh-key Webpage1-Test-Instance/* ubuntu@${{ secrets.INSTANCE_1_IP }}:/var/www/html/
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh-key ubuntu@${{ secrets.INSTANCE_1_IP }} "sudo systemctl restart apache2"

      - name: Deploy to Instance 2
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/ssh-key Webpage2-Test-Machine/* ubuntu@${{ secrets.INSTANCE_2_IP }}:/var/www/html/
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh-key ubuntu@${{ secrets.INSTANCE_2_IP }} "sudo systemctl restart httpd"
