name: Deploy to Web Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files: |
          Webpage1-Test-Instance/**
          Webpage2-Test-Machine/**
    - name: Debug File Structure
      run: ls -R ${{ github.workspace }}
        
    - name: Add Instance 1 to known_hosts
      if: contains(steps.changed-files.outputs.all_changed_files, 'Webpage1-Test-Instance/')
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.INSTANCE1_IP }} >> ~/.ssh/known_hosts

    - name: Deploy Webpage 1 to Instance 1
      if: contains(steps.changed-files.outputs.all_changed_files, 'Webpage1-Test-Instance/')
      uses: appleboy/ssh-action@v0.1.10  
      with:
        host: ${{ secrets.INSTANCE1_IP }}
        username: ${{ secrets.INSTANCE1_USER }}
        key: ${{ secrets.INSTANCE1_SSH_KEY }}
        script: |
          # Ensure /var/www/html exists
          sudo mkdir -p /var/www/html
          sudo chown -R $USER:$USER /var/www/html

    - name: Sync Webpage 1 to Instance 1 using rsync
      if: contains(steps.changed-files.outputs.all_changed_files, 'Webpage1-Test-Instance/')
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./Webpage1-Test-Instance/ \
        ${{ secrets.INSTANCE1_USER }}@${{ secrets.INSTANCE1_IP }}:/var/www/html/

    - name: Restart Nginx on Instance 1
      if: contains(steps.changed-files.outputs.all_changed_files, 'Webpage1-Test-Instance/')
      uses: appleboy/ssh-action@v0.1.10  
      with:
        host: ${{ secrets.INSTANCE1_IP }}
        username: ${{ secrets.INSTANCE1_USER }}
        key: ${{ secrets.INSTANCE1_SSH_KEY }}
        script: |
          sudo systemctl daemon-reload
          sudo systemctl restart nginx

    - name: Add Instance 2 to known_hosts
      if: contains(steps.changed-files.outputs.all_changed_files, 'Webpage2-Test-Machine/')
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.INSTANCE2_IP }} >> ~/.ssh/known_hosts

    - name: Deploy Webpage 2 to Instance 2
      if: contains(steps.changed-files.outputs.all_changed_files, 'Webpage2-Test-Machine/')
      uses: appleboy/ssh-action@v0.1.10  
      with:
        host: ${{ secrets.INSTANCE2_IP }}
        username: ${{ secrets.INSTANCE2_USER }}
        key: ${{ secrets.INSTANCE2_SSH_KEY }}
        script: |
          sudo mkdir -p /var/www/html
          sudo chown -R $USER:$USER /var/www/html

    - name: Sync Webpage 2 to Instance 2 using rsync
      if: contains(steps.changed-files.outputs.all_changed_files, 'Webpage2-Test-Machine/')
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./Webpage2-Test-Machine/ \
        ${{ secrets.INSTANCE2_USER }}@${{ secrets.INSTANCE2_IP }}:/var/www/html/

    - name: Restart Nginx on Instance 2
      if: contains(steps.changed-files.outputs.all_changed_files, 'Webpage2-Test-Machine/')
      uses: appleboy/ssh-action@v0.1.10  
      with:
        host: ${{ secrets.INSTANCE2_IP }}
        username: ${{ secrets.INSTANCE2_USER }}
        key: ${{ secrets.INSTANCE2_SSH_KEY }}
        script: |
          sudo systemctl daemon-reload
          sudo systemctl restart nginx
