name: Deploy to Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server:
          - { name: "ubuntu", ip: ${{ secrets.UBUNTU_IP }}, target: "/var/www/html/index.html" }
          - { name: "redhat", ip: ${{ secrets.REDHAT_IP }}, target: "/usr/share/nginx/html/index.html" }
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to ${{ matrix.server.name }} server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "index.html"
          target: ${{ matrix.server.target }}
